### ISSUE TITLE
Unable to create bam files

### ISSUE THREAD

**Issue by nilesh-iiita** [roland-rad-lab/MoCaSeq#1] opened 2020-08-18 22:15 UTC
No matter what dataset I try I am getting the same error and even with the test dataset.

The command I used is:
`sudo docker run -v ${working_directory}:/var/pipeline/ rolandradlab/mocaseq --test yes`
@sebastianlange 

+------------+
| FILE ERROR |
+------------+
Cannot access BAM file (/var/pipeline/MoCaSeq_Test/results/bam/MoCaSeq_Test.Tumor.bam).
It either does not exist or is not readable.

Please find the log file in the attachment. 
[MoCaSeq_Test.report.txt](https://github.com/roland-rad-lab/MoCaSeq/files/5093106/MoCaSeq_Test.report.txt)

**Comment by sebastianlange** [comment] 2020-08-19 07:56
Hi Nilesh,

Could you please provide the reference creation log:

ref/GRCm38.p6/GetReferenceData.txt

Best
Sebastian

On 19. Aug 2020, at 00:20, Nilesh Kumar <notifications@github.com> wrote:

﻿
No matter what dataset I try I am getting the same error and even with the test dataset.

The command I used is:
sudo docker run -v ${working_directory}:/var/pipeline/ rolandradlab/mocaseq --test yes
@sebastianlange

+------------+
| FILE ERROR |
+------------+
Cannot access BAM file (/var/pipeline/MoCaSeq_Test/results/bam/MoCaSeq_Test.Tumor.bam).
It either does not exist or is not readable.

Please find the log file in the attachment.
MoCaSeq_Test.report.txt

**Comment by nilesh-iiita** [comment] 2020-08-19 13:31
Hi @sebastianlange 
Please find the attached GetReferenceData.txt file.
[GetReferenceData.txt](https://github.com/roland-rad-lab/MoCaSeq/files/5096724/GetReferenceData.txt)

Thanks

**Comment by sebastianlange** [comment] 2020-08-19 13:45
OK, I know what the problem is, however I currently don’t have access to my workstation. Will update with a solution in 48h.

Best
Sebastian

On 19. Aug 2020, at 15:32, Nilesh Kumar <notifications@github.com> wrote:

﻿
Hi @sebastianlange
Please find the attached GetReferenceData.txt file.
GetReferenceData.txt

Thanks

**Comment by nilesh-iiita** [comment] 2020-08-24 17:25
Hi @sebastianlange,
Just checking, is docker updated?

Thanks

**Comment by sebastianlange** [comment] 2020-08-24 22:18
I have just committed a bugfix (https://github.com/roland-rad-lab/MoCaSeq/releases/tag/v0.4.53). The corresponding docker container has been successfully generated (0.4.53: https://hub.docker.com/repository/docker/rolandradlab/mocaseq/builds). 

1) Please remove the "ref" folder which was generated using an earlier iteration of the pipeline.
2) Pull the newest version: sudo docker pull rolandradlab/mocaseq:0.4.53 or :latest
3) Run the "test" sample again

Sorry for the inconvenience.

**Closed as completed** 2020-08-24 22:19 UTC
Labels: bug
